apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: juiceshop-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: dberdasco99/juiceshop-app
      ephemeral: true
      labels:
        - self-hosted
        - linux
        - x64
        - juiceshop
